<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Barang extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tb_barang')->insert([
            // AC Products
            [
                'nama_barang' => 'Daikin AC Inverter 1.5 PK',
                'harga' => 6000000.00,
                'diskon' => 700000.00,
                'harga_akhir' => 6000000.00 - 700000.00,
                'stok' => 30,
                'kategori_id' => 1,
                'deskripsi' => 'AC Daikin Inverter 1.5 PK, hemat energi dan ramah lingkungan',
                'gambar' => 'assets/images/barang/AC-DAIKIN.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Sharp AC 1.5 PK',
                'harga' => 5000000.00,
                'diskon' => 600000.00,
                'harga_akhir' => 5000000.00 - 600000.00,
                'stok' => 25,
                'kategori_id' => 1,
                'deskripsi' => 'AC Sharp 1.5 PK dengan teknologi Plasmacluster',
                'gambar' => 'assets/images/barang/AC-SHARP.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Samsung AC 1.5 PK',
                'harga' => 5500000.00,
                'diskon' => 800000.00,
                'harga_akhir' => 5500000.00 - 800000.00,
                'stok' => 25,
                'kategori_id' => 1,
                'deskripsi' => 'AC Samsung 1.5 PK dengan mode tidur otomatis',
                'gambar' => 'assets/images/barang/AC-SAMSUNG.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'LG Dual Inverter AC 1.5 PK',
                'harga' => 5800000.00,
                'diskon' => 500000.00,
                'harga_akhir' => 5800000.00 - 500000.00,
                'stok' => 20,
                'kategori_id' => 1,
                'deskripsi' => 'AC LG Dual Inverter 1.5 PK dengan efisiensi energi tinggi dan pendinginan cepat',
                'gambar' => 'assets/images/barang/AC-LG.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Panasonic Eco Smart AC 1 PK',
                'harga' => 4500000.00,
                'diskon' => 400000.00,
                'harga_akhir' => 4500000.00 - 400000.00,
                'stok' => 15,
                'kategori_id' => 1,
                'deskripsi' => 'Panasonic Eco Smart AC 1 PK dengan teknologi nanoe-G yang mampu menyaring bakteri',
                'gambar' => 'assets/images/barang/AC-Panasonic.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Mitsubishi Electric AC 1 PK',
                'harga' => 4800000.00,
                'diskon' => 450000.00,
                'harga_akhir' => 4800000.00 - 450000.00,
                'stok' => 18,
                'kategori_id' => 1,
                'deskripsi' => 'Mitsubishi Electric AC 1 PK dengan sistem aliran udara lebar dan hemat listrik',
                'gambar' => 'assets/images/barang/AC-Mitsubishi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Toshiba Inverter AC 1.5 PK',
                'harga' => 5300000.00,
                'diskon' => 600000.00,
                'harga_akhir' => 5300000.00 - 600000.00,
                'stok' => 22,
                'kategori_id' => 1,
                'deskripsi' => 'Toshiba Inverter AC 1.5 PK dengan teknologi inverter dan fitur auto-cleaning',
                'gambar' => 'assets/images/barang/AC-Mitsubishi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Hitachi Standard AC 1 PK',
                'harga' => 4700000.00,
                'diskon' => 350000.00,
                'harga_akhir' => 4700000.00 - 350000.00,
                'stok' => 12,
                'kategori_id' => 1,
                'deskripsi' => 'Hitachi Standard AC 1 PK, dilengkapi dengan filter anti-bakteri dan ramah lingkungan',
                'gambar' => 'assets/images/barang/AC-Panasonic.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Jasa Products
            [
                'nama_barang' => 'Jasa Instalasi AC',
                'harga' => 250000.00,
                'diskon' => 0.00,
                'harga_akhir' => 250000.00,
                'stok' => 100,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa instalasi AC untuk unit baru atau yang sudah ada',
                'gambar' => 'assets/images/barang/jasa-instalasi-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Servis AC',
                'harga' => 150000.00,
                'diskon' => 0.00,
                'harga_akhir' => 150000.00,
                'stok' => 100,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa servis dan perawatan AC untuk menjaga performa',
                'gambar' => 'assets/images/barang/jasa-servis-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Pembersihan AC',
                'harga' => 200000.00,
                'diskon' => 0.00,
                'harga_akhir' => 200000.00,
                'stok' => 80,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa pembersihan AC untuk menjaga kebersihan dan kesehatan udara',
                'gambar' => 'assets/images/barang/jasa-pembersihan-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Penggantian Filter AC',
                'harga' => 100000.00,
                'diskon' => 0.00,
                'harga_akhir' => 100000.00,
                'stok' => 90,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa penggantian filter AC untuk performa optimal',
                'gambar' => 'assets/images/barang/jasa-penggantian-filter-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Perbaikan AC',
                'harga' => 300000.00,
                'diskon' => 0.00,
                'harga_akhir' => 300000.00,
                'stok' => 50,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa perbaikan AC yang tidak berfungsi dengan baik',
                'gambar' => 'assets/images/barang/jasa-perbaikan-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Pemeliharaan Berkala AC',
                'harga' => 500000.00,
                'diskon' => 0.00,
                'harga_akhir' => 500000.00,
                'stok' => 30,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa pemeliharaan berkala untuk menjaga performa AC',
                'gambar' => 'assets/images/barang/jasa-pemeliharaan-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Konsultasi AC',
                'harga' => 250000.00,
                'diskon' => 0.00,
                'harga_akhir' => 250000.00,
                'stok' => 70,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa konsultasi untuk pemilihan AC yang tepat',
                'gambar' => 'assets/images/barang/jasa-konsultasi-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Perawatan AC Untuk Bisnis',
                'harga' => 750000.00,
                'diskon' => 0.00,
                'harga_akhir' => 750000.00,
                'stok' => 20,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa perawatan AC untuk skala bisnis dan komersial',
                'gambar' => 'assets/images/barang/jasa-perawatan-bisnis.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Audit Energi AC',
                'harga' => 400000.00,
                'diskon' => 0.00,
                'harga_akhir' => 400000.00,
                'stok' => 25,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa audit energi untuk efisiensi penggunaan AC',
                'gambar' => 'assets/images/barang/jasa-audit-energi.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Pemasangan Pipa AC',
                'harga' => 300000.00,
                'diskon' => 0.00,
                'harga_akhir' => 300000.00,
                'stok' => 40,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa pemasangan pipa AC sesuai standar',
                'gambar' => 'assets/images/barang/jasa-pemasangan-pipa-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Pemindahan Unit AC',
                'harga' => 350000.00,
                'diskon' => 0.00,
                'harga_akhir' => 350000.00,
                'stok' => 50,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa pemindahan unit AC ke lokasi baru dengan aman dan profesional',
                'gambar' => 'assets/images/barang/jasa-pemindahan-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Isi Ulang Freon AC',
                'harga' => 200000.00,
                'diskon' => 0.00,
                'harga_akhir' => 200000.00,
                'stok' => 60,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa isi ulang freon untuk menjaga performa pendinginan AC',
                'gambar' => 'assets/images/barang/jasa-isi-freon.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Jasa Kalibrasi AC',
                'harga' => 450000.00,
                'diskon' => 0.00,
                'harga_akhir' => 450000.00,
                'stok' => 35,
                'kategori_id' => 2,
                'deskripsi' => 'Jasa kalibrasi AC untuk meningkatkan efisiensi energi dan kinerja',
                'gambar' => 'assets/images/barang/jasa-kalibrasi-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Other Products
            [
                'nama_barang' => 'Filter AC',
                'harga' => 100000.00,
                'diskon' => 0.00,
                'harga_akhir' => 100000.00,
                'stok' => 200,
                'kategori_id' => 3,
                'deskripsi' => 'Filter AC untuk menjaga kebersihan udara',
                'gambar' => 'assets/images/barang/Filter-AC1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Remote AC Universal',
                'harga' => 75000.00,
                'diskon' => 0.00,
                'harga_akhir' => 75000.00,
                'stok' => 150,
                'kategori_id' => 3,
                'deskripsi' => 'Remote control universal untuk berbagai jenis AC',
                'gambar' => 'assets/images/barang/Remote-substitusi-universal.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Kipas Angin Portable',
                'harga' => 120000.00,
                'diskon' => 0.00,
                'harga_akhir' => 120000.00,
                'stok' => 80,
                'kategori_id' => 3,
                'deskripsi' => 'Kipas angin portable untuk ruangan kecil',
                'gambar' => 'assets/images/barang/kipas-angkot-portable.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Pembersih Udara',
                'harga' => 350000.00,
                'diskon' => 0.00,
                'harga_akhir' => 350000.00,
                'stok' => 60,
                'kategori_id' => 3,
                'deskripsi' => 'Pembersih udara dengan teknologi filter HEPA',
                'gambar' => 'assets/images/barang/pembersih-udara.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Penghangat Ruangan',
                'harga' => 600000.00,
                'diskon' => 0.00,
                'harga_akhir' => 600000.00,
                'stok' => 50,
                'kategori_id' => 3,
                'deskripsi' => 'Penghangat ruangan untuk cuaca dingin',
                'gambar' => 'assets/images/barang/penghangat-ruangan.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Duster AC',
                'harga' => 30000.00,
                'diskon' => 0.00,
                'harga_akhir' => 30000.00,
                'stok' => 120,
                'kategori_id' => 3,
                'deskripsi' => 'Duster untuk membersihkan AC dari debu',
                'gambar' => 'assets/images/barang/duster-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Kain Pembersih AC',
                'harga' => 20000.00,
                'diskon' => 0.00,
                'harga_akhir' => 20000.00,
                'stok' => 200,
                'kategori_id' => 3,
                'deskripsi' => 'Kain khusus untuk membersihkan AC',
                'gambar' => 'assets/images/barang/kain-pembersih-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Thermostat AC Digital',
                'harga' => 450000.00,
                'diskon' => 0.00,
                'harga_akhir' => 450000.00,
                'stok' => 30,
                'kategori_id' => 3,
                'deskripsi' => 'Thermostat digital untuk mengatur suhu AC',
                'gambar' => 'assets/images/barang/thermostat-digital.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Penjaga Suhu AC',
                'harga' => 250000.00,
                'diskon' => 0.00,
                'harga_akhir' => 250000.00,
                'stok' => 40,
                'kategori_id' => 3,
                'deskripsi' => 'Penjaga suhu otomatis untuk AC',
                'gambar' => 'assets/images/barang/penjaga-suhu-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Selang Pembuangan AC',
                'harga' => 50000.00,
                'diskon' => 0.00,
                'harga_akhir' => 50000.00,
                'stok' => 100,
                'kategori_id' => 3,
                'deskripsi' => 'Selang pembuangan untuk instalasi AC',
                'gambar' => 'assets/images/barang/selang-pembuangan-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Bracket AC',
                'harga' => 75000.00,
                'diskon' => 0.00,
                'harga_akhir' => 75000.00,
                'stok' => 70,
                'kategori_id' => 3,
                'deskripsi' => 'Bracket untuk pemasangan outdoor unit AC',
                'gambar' => 'assets/images/barang/bracket-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Penutup Outdoor AC',
                'harga' => 100000.00,
                'diskon' => 0.00,
                'harga_akhir' => 100000.00,
                'stok' => 50,
                'kategori_id' => 3,
                'deskripsi' => 'Penutup outdoor AC untuk melindungi dari debu dan hujan',
                'gambar' => 'assets/images/barang/penutup-outdoor-ac.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
