<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Barang extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tb_barang')->insert([
            // Kategori 1: Elektronik
            [
                'nama_barang' => 'PlayStation 5 Console Disc Version',
                'harga' => 8500000.00,
                'diskon' => 500000.00,
                'harga_akhir' => 8500000.00 - 500000.00,
                'stok' => 20,
                'kategori_id' => 1,
                'deskripsi' => 'Playstation Keluaran terbaru',
                'gambar' => 'assets/images/barang/ps5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Smart LED TV 55 inch',
                'harga' => 7500000.00,
                'diskon' => 1000000.00,
                'harga_akhir' => 7500000.00 - 1000000.00,
                'stok' => 15,
                'kategori_id' => 1,
                'deskripsi' => 'TV pintar dengan kualitas gambar yang tajam dan fitur canggih',
                'gambar' => 'assets/images/barang/TV.png', 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Kulkas 2 Pintu Samsung',
                'harga' => 4000000.00,
                'diskon' => 500000.00,
                'harga_akhir' => 4000000.00 - 500000.00,
                'stok' => 10,
                'kategori_id' => 1,
                'deskripsi' => 'Kulkas 2 pintu dengan teknologi pendinginan yang efisien',
                'gambar' => 'assets/images/barang/kulkas2pintu.png', 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Blender Philips HR2102/00',
                'harga' => 600000.00,
                'diskon' => 100000.00,
                'harga_akhir' => 600000.00 - 100000.00,
                'stok' => 50,
                'kategori_id' => 1,
                'deskripsi' => 'Blender berkualitas dengan daya tinggi untuk berbagai kebutuhan',
                'gambar' => 'assets/images/barang/blender.webp', 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kategori 2: Laptop
            [
                'nama_barang' => 'MacBook Air (M1 Chip)',
                'harga' => 11500000.00,
                'diskon' => 1500000.00,
                'harga_akhir' => 11500000.00 - 1500000.00,
                'stok' => 30,
                'kategori_id' => 2,
                'deskripsi' => 'MacBook Air dengan M1 Chip',
                'gambar' => 'assets/images/barang/macbook.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Dell XPS 13',
                'harga' => 13000000.00,
                'diskon' => 2000000.00,
                'harga_akhir' => 13000000.00 - 2000000.00,
                'stok' => 25,
                'kategori_id' => 2,
                'deskripsi' => 'Laptop Dell XPS 13 dengan desain premium dan performa tinggi',
                'gambar' => 'assets/images/barang/dell.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Asus ZenBook 14',
                'harga' => 11000000.00,
                'diskon' => 1200000.00,
                'harga_akhir' => 11000000.00 - 1200000.00,
                'stok' => 20,
                'kategori_id' => 2,
                'deskripsi' => 'Asus ZenBook 14 yang ringkas dengan daya tahan baterai lama',
                'gambar' => 'assets/images/barang/asus.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'HP Spectre x360',
                'harga' => 15000000.00,
                'diskon' => 2500000.00,
                'harga_akhir' => 15000000.00 - 2500000.00,
                'stok' => 15,
                'kategori_id' => 2,
                'deskripsi' => 'HP Spectre x360 dengan desain convertible dan kinerja yang luar biasa',
                'gambar' => 'assets/images/barang/hpscpectre.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kategori 3: Ponsel
            [
                'nama_barang' => 'Iphone 13 Pro 1Tb',
                'harga' => 8500000.00,
                'diskon' => 500000.00,
                'harga_akhir' => 8500000.00 - 500000.00,
                'stok' => 20,
                'kategori_id' => 3,
                'deskripsi' => 'Iphone 13 new',
                'gambar' => 'assets/images/barang/ip13.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Samsung Galaxy S21 Ultra',
                'harga' => 18000000.00,
                'diskon' => 2000000.00,
                'harga_akhir' => 18000000.00 - 2000000.00,
                'stok' => 25,
                'kategori_id' => 3,
                'deskripsi' => 'Samsung Galaxy S21 Ultra dengan kamera 108MP',
                'gambar' => 'assets/images/barang/s21u.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Samsung Galaxy S21 FE',
                'harga' => 9500000.00,
                'diskon' => 1000000.00,
                'harga_akhir' => 9500000.00 - 1000000.00,
                'stok' => 40,
                'kategori_id' => 3,
                'deskripsi' => 'Smartphone Samsung Galaxy S21 FE dengan kamera yang luar biasa',
                'gambar' => 'assets/images/barang/s21fe.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Xiaomi Mi 11',
                'harga' => 8000000.00,
                'diskon' => 1200000.00,
                'harga_akhir' => 8000000.00 - 1200000.00,
                'stok' => 35,
                'kategori_id' => 3,
                'deskripsi' => 'Xiaomi Mi 11 dengan layar AMOLED dan performa tinggi',
                'gambar' => 'assets/images/barang/xm11.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kategori 4: Fashion
            [
                'nama_barang' => 'Nike Air',
                'harga' => 1500000.00,
                'diskon' => 150000.00,
                'harga_akhir' => 1500000.00 - 150000.00,
                'stok' => 100,
                'kategori_id' => 4,
                'deskripsi' => 'Sepatu keren untuk semua orang',
                'gambar' => 'assets/images/barang/nike.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Adidas Ultraboost 21',
                'harga' => 2200000.00,
                'diskon' => 200000.00,
                'harga_akhir' => 2200000.00 - 200000.00,
                'stok' => 150,
                'kategori_id' => 3,
                'deskripsi' => 'Sepatu lari premium dari Adidas',
                'gambar' => 'assets/images/barang/adidasub21.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Levi\'s 501 Original Jeans',
                'harga' => 800000.00,
                'diskon' => 50000.00,
                'harga_akhir' => 800000.00 - 50000.00,
                'stok' => 50,
                'kategori_id' => 3,
                'deskripsi' => 'Jeans klasik dari Levi\'s',
                'gambar' => 'assets/images/barang/jeans.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Gucci T-Shirt',
                'harga' => 4000000.00,
                'diskon' => 300000.00,
                'harga_akhir' => 4000000.00 - 300000.00,
                'stok' => 10,
                'kategori_id' => 3,
                'deskripsi' => 'T-shirt eksklusif dari Gucci',
                'gambar' => 'assets/images/barang/gucci.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kategori 5: Kecantikan
            [
                'nama_barang' => 'Maybelline SuperStay Matte Ink',
                'harga' => 120000.00,
                'diskon' => 20000.00,
                'harga_akhir' => 120000.00 - 20000.00,
                'stok' => 300,
                'kategori_id' => 5,
                'deskripsi' => 'Lipstik matte tahan lama',
                'gambar' => 'https://images.maybelline.com/is/image/mny/face-makeup-superstay-matte-ink-liquid-lipstick-hero.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Estee Lauder Double Wear Foundation',
                'harga' => 600000.00,
                'diskon' => 50000.00,
                'harga_akhir' => 600000.00 - 50000.00,
                'stok' => 100,
                'kategori_id' => 5,
                'deskripsi' => 'Foundation tahan lama dari Estee Lauder',
                'gambar' => 'https://www.esteelauder.com/media/export/cms/products/558x768/el_sku_YFKN01_558x768_0.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'L\'Oreal Paris Revitalift',
                'harga' => 250000.00,
                'diskon' => 25000.00,
                'harga_akhir' => 250000.00 - 25000.00,
                'stok' => 200,
                'kategori_id' => 5,
                'deskripsi' => 'Krim wajah anti-aging dari L\'Oreal',
                'gambar' => 'https://www.lorealparisusa.com/-/media/project/loreal/brand-sites/oap/apac-products/skin-care/revitalift-serum/thumbnail/revitalift-hyaluronic-acid-anti-aging-serum.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Dior J\'adore Perfume',
                'harga' => 1200000.00,
                'diskon' => 100000.00,
                'harga_akhir' => 1200000.00 - 100000.00,
                'stok' => 50,
                'kategori_id' => 5,
                'deskripsi' => 'Parfum mewah dari Dior',
                'gambar' => 'https://www.dior.com/couture/var/dior/storage/images/3001-jadore-parfum/fond.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kategori 6: Household
            [
                'nama_barang' => 'Philips Blender HR2102/00',
                'harga' => 600000.00,
                'diskon' => 50000.00,
                'harga_akhir' => 600000.00 - 50000.00,
                'stok' => 75,
                'kategori_id' => 6,
                'deskripsi' => 'Blender Philips yang kuat dan tahan lama',
                'gambar' => 'assets/images/barang/blender.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Tefal Frying Pan',
                'harga' => 250000.00,
                'diskon' => 20000.00,
                'harga_akhir' => 250000.00 - 20000.00,
                'stok' => 50,
                'kategori_id' => 6,
                'deskripsi' => 'Panci penggorengan berkualitas tinggi dari Tefal',
                'gambar' => 'assets/images/barang/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Berkshire Blanket Throw',
                'harga' => 300000.00,
                'diskon' => 50000.00,
                'harga_akhir' => 300000.00 - 50000.00,
                'stok' => 100,
                'kategori_id' => 6,
                'deskripsi' => 'Selimut lembut dari Berkshire Blanket',
                'gambar' => 'https://berkshireblanket.com/wp-content/uploads/2020/09/blanket-throw-sleep.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kategori 7: Otomotif
                [
                    'nama_barang' => 'Pelindung Jok Mobil',
                    'harga' => 120000.00,
                    'diskon' => 15000.00,
                    'harga_akhir' => 120000.00 - 15000.00,
                    'stok' => 75,
                    'kategori_id' => 7,
                    'deskripsi' => 'Pelindung jok mobil untuk menjaga kebersihan interior.',
                    'gambar' => 'https://cdn.shopify.com/s/files/1/0328/1291/1596/products/Car-Seat-Cover_2048x2048.jpg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama_barang' => 'Kompas Mobil',
                    'harga' => 80000.00,
                    'diskon' => 10000.00,
                    'harga_akhir' => 80000.00 - 10000.00,
                    'stok' => 200,
                    'kategori_id' => 7,
                    'deskripsi' => 'Kompas mobil untuk membantu navigasi di perjalanan.',
                    'gambar' => 'https://cdn.shopify.com/s/files/1/0526/3523/5460/products/Compass_2048x2048.jpg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama_barang' => 'Lampu LED Mobil',
                    'harga' => 300000.00,
                    'diskon' => 50000.00,
                    'harga_akhir' => 300000.00 - 50000.00,
                    'stok' => 30,
                    'kategori_id' => 7,
                    'deskripsi' => 'Lampu LED untuk pencahayaan yang lebih terang di malam hari.',
                    'gambar' => 'https://cdn.shopify.com/s/files/1/0254/4885/0546/products/LED-Car-Lights_2048x2048.jpg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama_barang' => 'Dudukan Ponsel Mobil',
                    'harga' => 95000.00,
                    'diskon' => 15000.00,
                    'harga_akhir' => 95000.00 - 15000.00,
                    'stok' => 100,
                    'kategori_id' => 7,
                    'deskripsi' => 'Dudukan ponsel untuk memudahkan akses navigasi saat berkendara.',
                    'gambar' => 'https://cdn.shopify.com/s/files/1/0470/6236/4981/products/Car-Phone-Mount_2048x2048.jpg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
);

    }
}
